insert into tn_exercises (id, es, en, muscle_group, equipment, level, drive_id) values
('press-banca-plano', 'Press de banca plano', 'Flat Bench Press', 'Pecho', 'Barra', 'Intermedio', '18v1iO8crIFkL2-PdIrCD7l4tNhv4AAhY'),
('press-inclinado', 'Press de banca inclinado', 'Incline Bench Press', 'Pecho', 'Barra', 'Intermedio', '1DBunxRsGGpQDJNPT7Juv_5l-W6407rHW'),
('press-declinado', 'Press de banca declinado', 'Decline Bench Press', 'Pecho', 'Barra', 'Intermedio', '1UxZvR5tfaAhYKH-WrkPtxcBOyDaQGJkW'),
('press-plano-mancuernas', 'Press plano con mancuernas', 'Dumbbell Bench Press', 'Pecho', 'Mancuernas', 'Intermedio', '1xFt9Bo8TwVszcZ6zmvsSqHKEfbYNXn3S'),
('aperturas-mancuernas', 'Aperturas con mancuernas', 'Dumbbell Flyes', 'Pecho', 'Mancuernas', 'Principiante', '1301SGO-TckdmfSYX7FQQ8UUw7yVLDERH'),
('aperturas-inclinadas', 'Aperturas inclinadas', 'Incline Flyes', 'Pecho', 'Mancuernas', 'Principiante', '1s_XbPmJ_OldzhJ_rAe8GEd6j0OkDpPW5'),
('cruces-polea-alta', 'Cruces en polea alta', 'High Cable Crossover', 'Pecho', 'Polea', 'Intermedio', '1hSxlt9eZZaZvwY1CzEK5EunIKkxPQQad'),
('cruces-polea-media', 'Cruces en polea media', 'Mid Cable Crossover', 'Pecho', 'Polea', 'Intermedio', '1IeoMy-ePkI8udq3IrzUMi1x1tLi9dHJK'),
('cruces-polea-baja', 'Cruces en polea baja', 'Low Cable Crossover', 'Pecho', 'Polea', 'Intermedio', '1H5LQWvTY65kPFd-G54LYKyyxhvrMrPFH'),
('peck-deck', 'Peck deck', 'Pec Deck', 'Pecho', 'Máquina', 'Principiante', '1m5JKbTZ7PqRzJ6e3-54_uz2BbSjf3i8N'),
('press-convergente', 'Press convergente en máquina', 'Converging Machine Press', 'Pecho', 'Máquina', 'Principiante', '11UunlK7NZ9opC0DJkrUM5_C4mk0bxxfk'),
('fondos-pecho', 'Fondos para pecho', 'Chest Dips', 'Pecho', 'Peso corporal', 'Avanzado', '1K7HWCcVY-StrVzaJaZNqEnZOX9XzHADn'),
('flexiones', 'Flexiones', 'Push-ups', 'Pecho', 'Peso corporal', 'Principiante', '1Mse4sgM5NminTtAYcyu-Uy9GwhLYoPI3'),
('flexiones-inclinadas', 'Flexiones inclinadas', 'Incline Push-ups', 'Pecho', 'Peso corporal', 'Principiante', '1jlDVvU_F8yEtqwgKv8rgnjGfrt45hsaH'),
('dominadas', 'Dominadas', 'Pull-ups', 'Espalda', 'Peso corporal', 'Avanzado', '1qD8KMXI4PHhoBZJln99sIe3BiDOVE7EW'),
('dominadas-supinas', 'Dominadas supinas', 'Chin-ups', 'Espalda', 'Peso corporal', 'Avanzado', '17f2XWM2vbTq4ePQ9sGlI0Q0Q6KKtQJqz'),
('dominadas-asistidas', 'Dominadas asistidas', 'Assisted Pull-ups', 'Espalda', 'Máquina', 'Principiante', '1njm_nXvBWkM3QwBup9jb3HGy4w6_gD6q'),
('remo-barra', 'Remo con barra', 'Barbell Row', 'Espalda', 'Barra', 'Intermedio', '1hocmzRzXQghqEfCtaF_UWLDRKWME_e0b'),
('remo-hammer', 'Remo Hammer', 'Hammer Row', 'Espalda', 'Máquina', 'Intermedio', '1aH3n3hjDW7wO6HFzxAIFfqx65IioOIVw'),
('remo-maquina', 'Remo en máquina', 'Machine Row', 'Espalda', 'Máquina', 'Principiante', '1gcSOhmzmW8VLOvDFOa9P8Olbhqx0HKcB'),
('remo-t', 'Remo T', 'T-Bar Row', 'Espalda', 'Barra', 'Intermedio', '1-WpKxBxVbNlFXVJGh7DA5M1eV9tf7yJ_'),
('remo-banco-inclinado', 'Remo pecho apoyado en banco inclinado', 'Chest-Supported Row', 'Espalda', 'Mancuernas', 'Intermedio', '1jjhl37ChnWDnW3z_N8Qh1pxhnO-R9tTp'),
('remo-invertido', 'Remo invertido', 'Inverted Row', 'Espalda', 'Peso corporal', 'Principiante', '1pXdd1NPU295sDtZS1XR1QeNXg0-FqCEb'),
('jalon-pecho', 'Jalón al pecho', 'Lat Pulldown', 'Espalda', 'Polea', 'Principiante', '1DRmceZeWK34OQxkWIT134j2tSNdfZGaR'),
('jalon-trasnuca', 'Jalón tras nuca', 'Behind-Neck Pulldown', 'Espalda', 'Polea', 'Intermedio', '1t-QoEInKuTBUUiz4s7l21T2IEuT1p6R9'),
('jalon-cerrado', 'Jalón agarre cerrado', 'Close-Grip Pulldown', 'Espalda', 'Polea', 'Principiante', '1IYysjE2JfxQgDM6dr2rI1XvC_Zv1h6TD'),
('jalon-amplio', 'Jalón con agarre amplio', 'Wide-Grip Pulldown', 'Espalda', 'Polea', 'Principiante', '110zdWsMYJCpHkoj4j5d0mbWTqI9RBg2C'),
('pull-over', 'Pull over con mancuernas', 'Dumbbell Pullover', 'Espalda', 'Mancuernas', 'Intermedio', '132FTV3m0DqtHhBIg1KVcpmf35xMoAaya'),
('press-militar-barra', 'Press militar con barra', 'Barbell Overhead Press', 'Hombros', 'Barra', 'Intermedio', '1w9JrFaO-qUyCdTzLYt-NoLEgw6DaYLCX'),
('press-militar-mancuernas', 'Press militar con mancuernas', 'Dumbbell Shoulder Press', 'Hombros', 'Mancuernas', 'Intermedio', '1ezz57RwTHcCBTPy0Q4iEypc2I05tTkJT'),
('press-arnold', 'Press Arnold', 'Arnold Press', 'Hombros', 'Mancuernas', 'Intermedio', '1UVHfcyArqA7IDrnXSLJzlrely6FJU6fv'),
('press-hombros-maquina', 'Press de hombros en máquina', 'Machine Shoulder Press', 'Hombros', 'Máquina', 'Principiante', '1GFX9gnIQqk4yNwoS5RUM6FUMk26tGwNR'),
('elevaciones-laterales', 'Elevaciones laterales', 'Lateral Raises', 'Hombros', 'Mancuernas', 'Principiante', '1__l3wZvp3KjgaziJA3qP7cZWiAQesXQ_'),
('elevaciones-frontales', 'Elevaciones frontales', 'Front Raises', 'Hombros', 'Mancuernas', 'Principiante', '1q1UWlxi-8KcTpV94q5_YXRmzl7hVZkO8'),
('elevacion-frontal-disco', 'Elevación frontal con disco', 'Plate Front Raise', 'Hombros', 'Máquina', 'Principiante', '1NthPexkyAx0BtxHzUQVVn3ASUsjv3i9K'),
('remo-menton', 'Remo al mentón', 'Upright Row', 'Hombros', 'Barra', 'Intermedio', '1v5FeVcZ6Kz6MQHq_zzRG3HpZaey0LPub'),
('pajaros-mancuernas', 'Pájaros con mancuernas', 'Rear Delt Flyes', 'Hombros', 'Mancuernas', 'Principiante', '1TYBzOqvTY6Bdb19kihEUkb77LYg-VEWH'),
('pajaros-peck-deck', 'Pájaros en peck deck', 'Reverse Pec Deck', 'Hombros', 'Máquina', 'Principiante', '1OByJ30M-9GIPk994gb0M1UumcG9WwcEU'),
('face-pull-hombros', 'Face pull', 'Face Pull', 'Hombros', 'Polea', 'Principiante', '13R_Tw62u8De5njuoMTz9PMPCJis-YVvD'),
('y-raise', 'Y-Raise en banco inclinado', 'Incline Y-Raise', 'Hombros', 'Mancuernas', 'Intermedio', '1nvfUNsSnRADpdrJ4yuRC-f5vdx7-1qgb'),
('encogimientos', 'Encogimientos con mancuernas', 'Shrugs', 'Hombros', 'Mancuernas', 'Principiante', '19MaubIBIb4YfZ26OhfZ4Vnfd2EY5zUdT'),
('curl-barra-z', 'Curl con barra Z', 'EZ-Bar Curl', 'Bíceps', 'Barra', 'Principiante', '1pxojF3uzQpPZpIpKC91DaSkF4Cg5Kywc'),
('curl-barra-recta', 'Curl con barra recta', 'Straight Bar Curl', 'Bíceps', 'Barra', 'Principiante', '1Sz8VVHA3dWLgDMwmtwpGVMTmYCrrG4JQ'),
('curl-21', 'Curl 21', '21s', 'Bíceps', 'Barra', 'Intermedio', '19sqOfuN1IchIYcL-8dRSAk9sldPQ3M8S'),
('curl-21-z', 'Curl 21 con barra Z', 'EZ-Bar 21s', 'Bíceps', 'Barra', 'Intermedio', '1Fhvb2oYYv-kJjYa8CN4LqB3EWrSxYlX4'),
('curl-alternado', 'Curl alternado con mancuernas', 'Alternating Curl', 'Bíceps', 'Mancuernas', 'Principiante', '1teYYSwljtP6NYvRYec5va43M7R0jrjYB'),
('curl-inclinado', 'Curl inclinado con mancuernas', 'Incline Curl', 'Bíceps', 'Mancuernas', 'Intermedio', '17ujwBLa7f1M012jmp7-4iPPXaAowBmUQ'),
('curl-martillo', 'Curl martillo', 'Hammer Curl', 'Bíceps', 'Mancuernas', 'Principiante', '1tDu7HHdzvsWSK2OXcAXxePOrFRqNg9dt'),
('curl-martillo-mancuernas', 'Curl martillo con mancuernas', 'DB Hammer Curl', 'Bíceps', 'Mancuernas', 'Principiante', '1b_8gHrXndHfNJiCoFWdvECr9JBUGp8Ry'),
('curl-martillo-cuerda', 'Curl martillo con cuerda', 'Rope Hammer Curl', 'Bíceps', 'Polea', 'Principiante', '1RQDZXatJt0G8esMvsEtGR7DytFL_bnUa'),
('curl-concentrado', 'Curl concentrado', 'Concentration Curl', 'Bíceps', 'Mancuernas', 'Principiante', '1h-N-O94QI0oQiOyRBgmNcAanWt7yRozG'),
('curl-predicador', 'Curl predicador en máquina', 'Preacher Curl', 'Bíceps', 'Máquina', 'Intermedio', '1SN7aeq3B8TF4DkxsrmVskUCzfodRxkhZ'),
('curl-polea-baja', 'Curl en polea baja', 'Low Cable Curl', 'Bíceps', 'Polea', 'Principiante', '1VI6UhfDA9e0ci767B1-Ed07juMWgunvL'),
('curl-unilateral-polea', 'Curl unilateral en polea', 'Single-Arm Cable Curl', 'Bíceps', 'Polea', 'Intermedio', '1VYaMxwOEaZtdJuq43WgY3QYFJHywvbvW'),
('spider-curl', 'Spider curl', 'Spider Curl', 'Bíceps', 'Mancuernas', 'Intermedio', '1uQtQbKE03iSX2Jd70Nq1clslDA-_TAnC'),
('patada-triceps-polea', 'Patada de tríceps en polea', 'Cable Kickback', 'Tríceps', 'Polea', 'Principiante', '1_EDGF_Vuiw3_1syTlxk3y5n6JAaWMUa4'),
('pres-frances-z', 'Press francés con barra Z', 'EZ-Bar Skullcrusher', 'Tríceps', 'Barra', 'Intermedio', '1Frc04Ik9fpEZCFt15Go68eEpPOboFYjD'),
('pres-frances-mancuernas', 'Press francés con mancuernas', 'DB Skullcrusher', 'Tríceps', 'Mancuernas', 'Intermedio', '1SVL-m1-IVvz-LZCSjeUrna7R1zf8t3Kh'),
('extension-triceps-mancuernas', 'Extensión de tríceps con mancuernas', 'Overhead Extension', 'Tríceps', 'Mancuernas', 'Intermedio', '1LWFbYDTMwegFrIr_M8pBYJrFpr5PbFcd'),
('extension-unilateral-polea', 'Extensión unilateral en polea', 'Single-Arm Pushdown', 'Tríceps', 'Polea', 'Principiante', '1O_NnnrxjYL_DPO_bRp3YY3CKPZd55wnk'),
('extension-triceps-unilateral', 'Extensión de tríceps unilateral con mancuerna', 'Single-Arm Overhead Ext.', 'Tríceps', 'Mancuernas', 'Intermedio', '16wBUvQMROJvgZyEj_1APY80tgiCHY5NG'),
('press-triceps-maquina', 'Press de tríceps en máquina', 'Machine Tricep Press', 'Tríceps', 'Máquina', 'Principiante', '1CTpZOtvnCS-6pThE6-QDRKX6KoJ0FN97'),
('press-cerrado', 'Press cerrado en banco plano', 'Close-Grip Bench', 'Tríceps', 'Barra', 'Intermedio', '10yq7zR1JZo_QglRpA6H3AVZe_a4d9-Kq'),
('fondos-paralelas', 'Fondos en paralelas', 'Parallel Bar Dips', 'Tríceps', 'Peso corporal', 'Avanzado', '1yIrJzmkY6QmVMqyM7qlTVTF6pdKJw5GF'),
('sentadilla-libre', 'Sentadilla libre', 'Back Squat', 'Cuádriceps', 'Barra', 'Intermedio', '1CDy1MH2wVptnsYsNF4OaV81F8quvge_z'),
('sentadilla-frontal', 'Sentadilla frontal', 'Front Squat', 'Cuádriceps', 'Barra', 'Avanzado', '1z6OEToCPUbjsUrZ3vfRsxZfR99jrzN-C'),
('sentadilla-goblet', 'Sentadilla goblet', 'Goblet Squat', 'Cuádriceps', 'Mancuernas', 'Principiante', '1qGiO0eJ4-GSEpgjdws0KJW7n4NmNGt3o'),
('sentadilla-hack', 'Sentadilla hack', 'Hack Squat', 'Cuádriceps', 'Máquina', 'Intermedio', '10N18v24s7-YPj-x55NhlPi3R8WsjezIW'),
('sentadilla-sumo', 'Sentadilla sumo', 'Sumo Squat', 'Cuádriceps', 'Mancuernas', 'Principiante', '1MYTQxGgnTP0TEf91lD9UCFcX1CHOGSq9'),
('prensa-45', 'Prensa 45°', 'Leg Press 45°', 'Cuádriceps', 'Máquina', 'Principiante', '1imGcPj51jVnGC5St7cXO2rbM5V295RV1'),
('prensa-90', 'Prensa 90°', 'Leg Press 90°', 'Cuádriceps', 'Máquina', 'Principiante', '1seDFemrPQiCnsvfDv9Jx6geNnqGUPsr3'),
('extension-cuadriceps', 'Extensión de cuádriceps', 'Leg Extension', 'Cuádriceps', 'Máquina', 'Principiante', '1EZMg-s7VjlKGfcrSFIBFboygGCb_61ik'),
('zancadas', 'Zancadas estáticas', 'Static Lunges', 'Cuádriceps', 'Mancuernas', 'Principiante', '1P87lzmzDgmwF3Yd1w8OJ9UxJmssVUlFq'),
('step-up', 'Step up', 'Step Up', 'Cuádriceps', 'Mancuernas', 'Principiante', '1ETY_5miiaCnTSS_tTj0-Fl8WGyZqtNJf'),
('sentadilla-bulgara', 'Sentadilla búlgara', 'Bulgarian Split Squat', 'Cuádriceps', 'Mancuernas', 'Intermedio', '17D9vYhxlBktRm4OEWm3hp_C2TYFtm4Vv'),
('peso-muerto-rumano', 'Peso muerto rumano', 'Romanian Deadlift', 'Isquios', 'Barra', 'Intermedio', '1UYfvJFICT4vOwyy5VaK22bU7PaPqnqIJ'),
('buenos-dias', 'Buenos días con barra', 'Good Mornings', 'Isquios', 'Barra', 'Intermedio', '12nJX9oIwR46m-JbrBtwOPsf6b-qE_37E'),
('curl-femoral-pie', 'Curl femoral de pie', 'Standing Leg Curl', 'Isquios', 'Máquina', 'Principiante', '1DCTPagVgxDvL_IMzz9QDdMKN5bz4WjUF'),
('curl-femoral-acostado', 'Curl femoral acostado', 'Lying Leg Curl', 'Isquios', 'Máquina', 'Principiante', '1PsoytRb0EQ0c3kxYfV3yB9xaTTuw92eZ'),
('curl-femoral-sentado', 'Curl femoral sentado', 'Seated Leg Curl', 'Isquios', 'Máquina', 'Principiante', '1Qt8YukDoVrPXuFZ8EIWgJc-szqc0_tBh'),
('curl-nordico', 'Curl nórdico', 'Nordic Curl', 'Isquios', 'Peso corporal', 'Avanzado', '1R7zT7nJTf76oRaExexGItQ8Ocu8jwa-4'),
('pull-through', 'Pull through en polea', 'Cable Pull-Through', 'Isquios', 'Polea', 'Principiante', '10w765IPm-croftZ-c8Ffa4v9xHA3Q4i3'),
('hip-thrust', 'Hip thrust', 'Hip Thrust', 'Glúteos', 'Barra', 'Intermedio', '1FtA7t74mYOI8IVF5nzzU2ceogqjy21N_'),
('hip-thrust-unilateral', 'Hip thrust unilateral', 'Single-Leg Hip Thrust', 'Glúteos', 'Peso corporal', 'Intermedio', '18U7w20nvyw5acHsEXdJhrODMmD01a1Sq'),
('puente-gluteos', 'Puente de glúteos', 'Glute Bridge', 'Glúteos', 'Peso corporal', 'Principiante', '1tjOeOcyyfMXtXJq-psaiSEGCblsR9enr'),
('patada-gluteos-polea', 'Patada de glúteos en polea', 'Cable Glute Kickback', 'Glúteos', 'Polea', 'Principiante', '13soSnnTHFQ1sVaHSGppt6MGMd6v7VCs_'),
('abduccion-banda', 'Abducción con banda', 'Band Abduction', 'Glúteos', 'Peso corporal', 'Principiante', '1Gl0wX5vegPlWk0ux-DmQW1yo-pgAF_GJ'),
('abduccion-maquina', 'Abducción de cadera en máquina', 'Hip Abduction Machine', 'Glúteos', 'Máquina', 'Principiante', '1m2PsojtzILeNjVaH0nRDbndl0q1FbFyF'),
('aduccion-maquina', 'Aducción en máquina', 'Hip Adduction Machine', 'Glúteos', 'Máquina', 'Principiante', '1mkoLKAVqE28NTzPDbKHmng4vqA83lGYO'),
('frogs-pumps', 'Frogs pumps con banda', 'Frog Pumps', 'Glúteos', 'Peso corporal', 'Principiante', '1qouRG8tYEUO1daIYDD06lSh_EHNnJmlF'),
('peso-muerto-convencional', 'Peso muerto convencional', 'Conventional Deadlift', 'Glúteos', 'Barra', 'Avanzado', '1GgJ7px7C_vZogIKBBEp3_4hxCUFTfLOK'),
('peso-muerto-sumo', 'Peso muerto sumo', 'Sumo Deadlift', 'Glúteos', 'Barra', 'Avanzado', '1N9ovpGcbGwhA5yue0P2P19daVJu4y8Gq'),
('peso-muerto-unilateral', 'Peso muerto unilateral', 'Single-Leg Deadlift', 'Glúteos', 'Mancuernas', 'Intermedio', '1MyX3nmm7OJYPt_AauHSKU5qtoQpNrEfY'),
('elevacion-talones', 'Elevación de talones de pie', 'Standing Calf Raise', 'Gemelos', 'Máquina', 'Principiante', '1dm2vyVF8-a3OUf1pTisEzInjOA4aU9zS')
on conflict (id) do update set es=excluded.es, en=excluded.en, muscle_group=excluded.muscle_group, equipment=excluded.equipment, level=excluded.level, drive_id=excluded.drive_id;